// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7zZfMctFv5Om1hZv0K_wlWqLxkAT_b8',
    appId: '1:789092768980:web:14bb590736911b8f2caf41',
    messagingSenderId: '789092768980',
    projectId: 'asksr-eb5a9',
    authDomain: 'asksr-eb5a9.firebaseapp.com',
    storageBucket: 'asksr-eb5a9.firebasestorage.app',
    measurementId: 'G-J2DM5P95VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6-BclhjDoUwxxqBp7x5XeyVVLt8b1fs',
    appId: '1:789092768980:android:edb0ad62f7e595f22caf41',
    messagingSenderId: '789092768980',
    projectId: 'asksr-eb5a9',
    storageBucket: 'asksr-eb5a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKK0EmGSEeRoolzx5fkxI3O9M_vuB85M',
    appId: '1:789092768980:ios:8fd43af5d51f1c982caf41',
    messagingSenderId: '789092768980',
    projectId: 'asksr-eb5a9',
    storageBucket: 'asksr-eb5a9.firebasestorage.app',
    iosBundleId: 'com.example.asksr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKK0EmGSEeRoolzx5fkxI3O9M_vuB85M',
    appId: '1:789092768980:ios:8fd43af5d51f1c982caf41',
    messagingSenderId: '789092768980',
    projectId: 'asksr-eb5a9',
    storageBucket: 'asksr-eb5a9.firebasestorage.app',
    iosBundleId: 'com.example.asksr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM7zZfMctFv5Om1hZv0K_wlWqLxkAT_b8',
    appId: '1:789092768980:web:9efee27688a34a272caf41',
    messagingSenderId: '789092768980',
    projectId: 'asksr-eb5a9',
    authDomain: 'asksr-eb5a9.firebaseapp.com',
    storageBucket: 'asksr-eb5a9.firebasestorage.app',
    measurementId: 'G-HMSXRFQ7N7',
  );
}
